version: "3.10.15"
services:
  neuralami:
    container_name: neuralami
    restart: always
    image: vikasrij/neuralami:v1.0
    networks:
      - db_network
      - web_network
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.0.12
    container_name: redis
    command: ["redis-server", "--port", "6379", "--slave-read-only", "no"]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network

  celery:
    container_name: celery
    restart: always
    image: celery:5.3
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - db_network
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
      PYTHONPATH: /app
    command: celery -A apps.tasks worker -l info -B
    depends_on:
      - neuralami
      - redis

networks:
  db_network:
    driver: bridge

  web_network:
    driver: bridge
