version: "3.10.15"
services:
  neuralami:
    container_name: neuralami
    restart: always
    build:
      context: .
    networks:
      - db_network
      - web_network
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - redis  # Ensure Redis is available before starting the app

  redis:
    image: redis:7.0.12
    container_name: redis
    command: ["redis-server", "--port", "6379", "--slave-read-only", "no"]
    restart: always
    ports:
      - 6379:6379
    networks:
      - db_network
  celery:
    container_name: celery
    restart: always
    build:
      context: .
    env_file:
      - .env  
    networks:
      - db_network
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings"
    command: "celery -A apps.tasks worker -l info -B"
    depends_on:
      - neuralami

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
