version: "3.9"
services:
  neuralami:
    environment:
      - DEBUG=False
    deploy:
      restart_policy:
        condition: any
    
  celery_worker:
    deploy:
      restart_policy:
        condition: any

  celery_beat:
    deploy:
      restart_policy:
        condition: any 