# Generated by Django 5.1.6 on 2025-03-14 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummarizerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('compressed_content', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('content_token_size', models.IntegerField()),
                ('content_character_count', models.IntegerField()),
                ('total_input_tokens', models.IntegerField()),
                ('total_output_tokens', models.IntegerField()),
                ('model_used', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summarizer_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
