# Generated by Django 5.1.5 on 2025-01-27 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
