# Generated by Django 5.1.2 on 2025-01-18 21:15

import apps.image_optimizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_optimizer', '0002_optimizationjob_optimizedimage_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedimage',
            name='optimized_file',
            field=models.FileField(upload_to=apps.image_optimizer.models.user_optimized_path),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='original_file',
            field=models.FileField(upload_to=apps.image_optimizer.models.user_original_path),
        ),
    ]
