# Generated by Django 5.1.6 on 2025-03-06 17:28

import apps.image_optimizer.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_optimizer', '0003_alter_optimizedimage_optimized_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedimage',
            name='optimized_file',
            field=models.FileField(storage=core.storage.SecureFileStorage(collection='image_optimizer/optimized_images', private=True), upload_to=apps.image_optimizer.models.user_optimized_path),
        ),
        migrations.AlterField(
            model_name='optimizedimage',
            name='original_file',
            field=models.FileField(storage=core.storage.SecureFileStorage(collection='image_optimizer/original_images', private=True), upload_to=apps.image_optimizer.models.user_original_path),
        ),
    ]
