# Generated by Django 5.1.6 on 2025-03-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_optimizer', '0004_add_secure_file_storage'),
        ('organizations', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationjob',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='optimizedimage',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
    ]
