# Generated by Django 5.1.6 on 2025-03-06 17:28

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0025_alter_client_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoproject',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, storage=core.storage.SecureFileStorage(collection='seo_projects', private=True), upload_to=''),
        ),
    ]
