# Generated by Django 5.1.6 on 2025-03-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0026_add_secure_file_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummarizerUsage',
        ),
    ]
