# Generated by Django 5.1.7 on 2025-03-31 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_manager', '0027_delete_summarizerusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, help_text='The specific Google Ads Customer ID (e.g., 123-456-7890)', max_length=100, null=True)),
                ('login_customer_id', models.CharField(blank=True, help_text='The Manager Account ID (MCC) used for login, if applicable.', max_length=100, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.URLField(blank=True, null=True)),
                ('ads_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ads_credentials', to='seo_manager.client')),
            ],
        ),
    ]
