# Generated by Django 5.1.2 on 2025-01-07 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('provider_type', models.CharField(choices=[('litellm', 'LiteLLM'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama')], default='litellm', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_base_url', models.URLField(blank=True)),
                ('organization_id', models.CharField(blank=True, max_length=255)),
                ('default_model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('default_temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('timeout', models.IntegerField(default=30)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('tokens_per_minute', models.IntegerField(default=90000)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay', models.FloatField(default=1.0)),
                ('fallback_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_configs', to='common.llmconfiguration')),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
                'indexes': [models.Index(fields=['provider_type', 'is_active'], name='common_llmc_provide_ef1ca0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(blank=True, max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('provider_type', models.CharField(blank=True, choices=[('litellm', 'LiteLLM'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama')], max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='common_toke_user_id_0272bd_idx'), models.Index(fields=['model', 'timestamp'], name='common_toke_model_1ccdbc_idx'), models.Index(fields=['provider_type', 'timestamp'], name='common_toke_provide_d4b398_idx')],
            },
        ),
    ]
