# Generated by Django 5.1.2 on 2025-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_llmconfiguration_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfiguration',
            name='cost_per_1k_completion_tokens',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Cost per 1,000 completion tokens in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='cost_per_1k_prompt_tokens',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Cost per 1,000 prompt tokens in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='model_family',
            field=models.CharField(choices=[('gpt4', 'GPT-4'), ('gpt35', 'GPT-3.5'), ('claude3', 'Claude 3'), ('claude2', 'Claude 2'), ('gemini', 'Gemini'), ('llama', 'Llama'), ('mistral', 'Mistral'), ('custom', 'Custom')], default='gpt35', max_length=20),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='stream_buffer_size',
            field=models.IntegerField(default=1024, help_text='Maximum size of streaming buffer in bytes'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='stream_chunk_size',
            field=models.IntegerField(default=100, help_text='Size of chunks to buffer in streaming mode'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='stream_timeout',
            field=models.IntegerField(default=60, help_text='Streaming timeout in seconds'),
        ),
        migrations.AddField(
            model_name='llmconfiguration',
            name='supports_streaming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='llmconfiguration',
            index=models.Index(fields=['model_family', 'is_active'], name='common_llmc_model_f_6efd5a_idx'),
        ),
    ]
