# Generated by Django 5.1.2 on 2025-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_llmconfiguration_cost_per_1k_completion_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMTestHarnessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'LLM Test Harness',
                'managed': False,
            },
        ),
    ]
