# Generated by Django 5.1.2 on 2025-01-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_llmtestharnessmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmtestharnessmodel',
            options={'managed': False, 'verbose_name': 'LLM Test Harness', 'verbose_name_plural': 'LLM Test Harness'},
        ),
    ]
