# Generated by Django 5.1.2 on 2025-01-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_llmconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='model_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Default parameters for model (temperature, top_p, etc.)', null=True),
        ),
    ]
