# Generated by Django 5.1.2 on 2025-01-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_llmconfiguration_model_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfiguration',
            name='provider_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific settings and overrides', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfiguration',
            name='streaming_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for streaming responses', null=True),
        ),
    ]
