# Generated by Django 5.1.2 on 2025-01-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_llmconfiguration_provider_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llmconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLM Configuration', 'verbose_name_plural': 'LLM Configurations'},
        ),
        migrations.RemoveField(
            model_name='llmconfiguration',
            name='is_active',
        ),
    ]
