# Generated by Django 5.1.6 on 2025-03-06 17:28

import apps.users.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SecureFileStorage(collection='user_avatars', private=True), upload_to=apps.users.models.avatar_with_id),
        ),
    ]
