# Generated by Django 5.1.2 on 2024-12-20 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last30dKeysBySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField(null=True)),
                ('key_alias', models.TextField(null=True)),
                ('key_name', models.TextField(null=True)),
                ('total_spend', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Last30dKeysBySpend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Last30dModelsBySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(null=True)),
                ('total_spend', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Last30dModelsBySpend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Last30dTopEndUsersSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_user', models.TextField(null=True)),
                ('total_events', models.BigIntegerField(null=True)),
                ('total_spend', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'Last30dTopEndUsersSpend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiteLLMSpendLog',
            fields=[
                ('request_id', models.TextField(primary_key=True, serialize=False)),
                ('call_type', models.TextField()),
                ('api_key', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('spend', models.FloatField(db_column='spend', default=0.0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('completionStartTime', models.DateTimeField(null=True)),
                ('model', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('model_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('model_group', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('api_base', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('user', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('metadata', models.JSONField(default=dict, null=True)),
                ('cache_hit', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('cache_key', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('request_tags', models.JSONField(default=list, null=True)),
                ('team_id', models.TextField(null=True)),
                ('end_user', models.TextField(null=True)),
                ('requester_ip_address', models.TextField(null=True)),
            ],
            options={
                'db_table': 'LiteLLM_SpendLogs',
                'managed': False,
            },
        ),
    ]
