# Generated by Django 5.1.2 on 2024-12-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='last30dkeysbyspend',
            options={'default_permissions': (), 'managed': False, 'ordering': ['-total_spend']},
        ),
        migrations.AlterModelOptions(
            name='last30dmodelsbyspend',
            options={'default_permissions': (), 'managed': False, 'ordering': ['-total_spend']},
        ),
        migrations.AlterModelOptions(
            name='last30dtopendusersspend',
            options={'default_permissions': (), 'managed': False, 'ordering': ['-total_spend']},
        ),
        migrations.AlterModelOptions(
            name='litellmspendlog',
            options={'default_permissions': (), 'managed': False},
        ),
    ]
