# Generated by Django 4.2.9 on 2024-10-11 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_crewtask_crew_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='input_variables',
            field=models.JSONField(blank=True, null=True, default=list, help_text='List of input variables required for crew execution'),
        ),
    ]
