# Generated by Django 5.1.2 on 2024-12-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0038_alter_agent_function_calling_llm_alter_agent_llm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation'),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to='agents.conversation'),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to='agents.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.UUIDField(),
        ),
    ]
