# Generated by Django 5.1.2 on 2024-12-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_chatmessage_conversation_toolrun_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.conversation'),
            preserve_default=False,
        ),
    ]
