# Generated by Django 5.1.2 on 2024-12-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_alter_chatmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_runs', to='agents.chatmessage'),
        ),
    ]
