# Generated by Django 5.1.2 on 2024-12-21 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0041_alter_toolrun_conversation_alter_toolrun_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='model',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='agents_chat_convers_fc5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id'], name='agents_chat_session_3cebdc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_deleted'], name='agents_chat_is_dele_4514f3_idx'),
        ),
    ]
