# Generated by Django 5.1.2 on 2024-12-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0043_userslackintegration'),
        ('seo_manager', '0023_searchconsolecredentials_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackChannelClientMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32)),
                ('team_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seo_manager.client')),
            ],
            options={
                'db_table': 'slack_channel_client_mappings',
                'unique_together': {('channel_id', 'team_id')},
            },
        ),
    ]
