# Generated by Django 5.1.2 on 2025-01-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0044_slackchannelclientmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='crew_execution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversation', to='agents.crewexecution'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='participant_type',
            field=models.CharField(choices=[('agent', 'Agent Chat'), ('crew', 'Crew Chat')], default='agent', max_length=50),
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CrewChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cleaned', 'Cleaned')], default='active', max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crew_chat_session', to='agents.conversation')),
                ('crew_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='agents.crewexecution')),
            ],
            options={
                'indexes': [models.Index(fields=['last_activity', 'status'], name='agents_crew_last_ac_cc1c9a_idx')],
            },
        ),
    ]
