# Generated by Django 5.1.2 on 2025-01-18 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0045_conversation_crew_execution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewexecution',
            name='inputs',
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_executions', to='agents.conversation'),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='task_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crewexecution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
