# Generated by Django 5.1.2 on 2025-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0047_crewexecution_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
