# Generated by Django 5.1.5 on 2025-01-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0048_chatmessage_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='crew_execution',
        ),
    ]
