# Generated by Django 5.1.5 on 2025-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0049_remove_task_crew_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrun',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
