# Generated by Django 5.1.5 on 2025-01-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0050_toolrun_is_deleted'),
    ]

    operations = [
        # No operations needed since the field is already a JSONField
    ]
