# Generated by Django 5.1.5 on 2025-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0050_toolrun_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='input_variables',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
