# Generated by Django 5.1.5 on 2025-02-10 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0051_alter_crew_input_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('state_schema', models.JSONField(help_text='JSON schema for flow state validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pipelineroute',
            name='target_pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelineexecution',
            name='pipeline',
        ),
        migrations.RemoveField(
            model_name='pipelineexecution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pipelinerunresult',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='pipelineroute',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='crew',
        ),
        migrations.AlterField(
            model_name='agent',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-pro-exp-02-05', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.CharField(default='gemini/gemini-2.0-pro-exp-02-05', max_length=100),
        ),
        migrations.AlterField(
            model_name='crew',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-pro-exp-02-05', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-pro-exp-02-05', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-pro-exp-02-05', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FlowCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('trigger_condition', models.TextField(blank=True, help_text='Python condition for triggering this crew')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.crew')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.flow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='crews',
            field=models.ManyToManyField(through='agents.FlowCrew', to='agents.crew'),
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.flow')),
            ],
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
        migrations.DeleteModel(
            name='PipelineExecution',
        ),
        migrations.DeleteModel(
            name='PipelineRunResult',
        ),
        migrations.DeleteModel(
            name='PipelineRoute',
        ),
        migrations.DeleteModel(
            name='PipelineStage',
        ),
    ]
