# Generated by Django 5.1.5 on 2025-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0052_flow_remove_pipelineroute_target_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-flash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.CharField(default='gemini/gemini-2.0-flash', max_length=100),
        ),
        migrations.AlterField(
            model_name='crew',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-flash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-flash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.0-flash', max_length=100, null=True),
        ),
    ]
