# Generated by Django 5.1.6 on 2025-03-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0054_alter_conversation_crew_execution'),
        ('organizations', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewtask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
