# Generated by Django 5.1.6 on 2025-03-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0055_crewtask_organization'),
        ('organizations', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewtask',
            name='organization',
        ),
        migrations.AddField(
            model_name='crewexecution',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
        ),
    ]
