# Generated by Django 5.1.7 on 2025-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0056_remove_crewtask_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.5-pro-exp-03-25', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='llm',
            field=models.CharField(default='gemini/gemini-2.5-pro-exp-03-25', max_length=100),
        ),
        migrations.AlterField(
            model_name='crew',
            name='function_calling_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.5-pro-exp-03-25', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='manager_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.5-pro-exp-03-25', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='planning_llm',
            field=models.CharField(blank=True, default='gemini/gemini-2.5-pro-exp-03-25', max_length=100, null=True),
        ),
    ]
