# Generated by Django 5.1.2 on 2025-01-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_website', '0003_crawlresult_result_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlresult',
            name='links_to_visit',
        ),
        migrations.RemoveField(
            model_name='crawlresult',
            name='result_file_path',
        ),
        migrations.AlterField(
            model_name='crawlresult',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crawlresult',
            name='links_visited',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='crawlresult',
            name='total_links',
            field=models.IntegerField(default=0),
        ),
    ]
