# Generated by Django 5.1.2 on 2025-01-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_website', '0004_remove_crawlresult_links_to_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlresult',
            name='content',
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='file_path',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
    ]
