# Generated by Django 5.1.5 on 2025-02-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_website', '0005_remove_crawlresult_content_crawlresult_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlresult',
            name='file_path',
        ),
    ]
