version: '3.8'

services:
  playwright-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - API_KEY=your_api_key_here  # Change this in production
    restart: unless-stopped
    # Healthcheck is now defined in the Dockerfile
    # but we keep it here for Docker Compose compatibility
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
