# Generated by Django 5.1.2 on 2024-12-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo_manager', '0023_searchconsolecredentials_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('website', models.URLField()),
                ('max_pages', models.IntegerField(default=100)),
                ('check_external_links', models.BooleanField(default=False)),
                ('crawl_delay', models.FloatField(default=1.0)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('progress', models.JSONField(default=dict, help_text='Stores progress information during the audit')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_audits', to='seo_manager.client')),
            ],
            options={
                'ordering': ['-start_time'],
                'get_latest_by': 'start_time',
            },
        ),
        migrations.CreateModel(
            name='SEOAuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('broken_link', 'Broken Link'), ('meta_missing', 'Missing Meta Tags'), ('duplicate_content', 'Duplicate Content'), ('ssl_issue', 'SSL Issue'), ('mobile_unfriendly', 'Mobile Unfriendly'), ('slow_loading', 'Slow Loading'), ('missing_alt', 'Missing Alt Text'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('url', models.URLField()),
                ('details', models.JSONField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='seo_audit.seoauditresult')),
            ],
            options={
                'ordering': ['-severity', '-discovered_at'],
            },
        ),
    ]
