# Generated by Django 5.1.2 on 2025-01-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoauditissue',
            name='issue_type',
            field=models.CharField(choices=[('title', 'Title Tag Issues'), ('meta_description', 'Meta Description Issues'), ('h1', 'H1 Tag Issues'), ('404', '404 Page Issues'), ('broken_link', 'Broken Link'), ('missing_alt', 'Missing Alt Text'), ('short_alt', 'Short Alt Text'), ('missing_dimensions', 'Missing Image Dimensions'), ('generic_filename', 'Generic Image Filename'), ('large_size', 'Large Image Size'), ('no_lazy_loading', 'No Lazy Loading'), ('no_srcset', 'Missing Srcset'), ('thin_content', 'Thin Content'), ('duplicate_content', 'Duplicate Content'), ('canonical_missing', 'Missing Canonical'), ('canonical_invalid_format', 'Invalid Canonical Format'), ('canonical_different', 'Different Canonical URL'), ('canonical_relative', 'Relative Canonical URL'), ('canonical_multiple', 'Multiple Canonical Tags'), ('canonical_on_pagination', 'Canonical on Pagination'), ('canonical_chain', 'Canonical Chain'), ('og_title_missing', 'Missing OG Title'), ('og_description_missing', 'Missing OG Description'), ('og_image_missing', 'Missing OG Image'), ('og_image_invalid', 'Invalid OG Image'), ('twitter_card_missing', 'Missing Twitter Card'), ('twitter_card_invalid', 'Invalid Twitter Card'), ('twitter_title_missing', 'Missing Twitter Title'), ('twitter_description_missing', 'Missing Twitter Description'), ('twitter_image_missing', 'Missing Twitter Image'), ('twitter_image_invalid', 'Invalid Twitter Image'), ('sitemap_http_error', 'Sitemap HTTP Error'), ('missing_url', 'Missing URL in Sitemap'), ('invalid_url', 'Invalid URL Format'), ('invalid_lastmod', 'Invalid Lastmod Date'), ('invalid_changefreq', 'Invalid Change Frequency'), ('invalid_priority', 'Invalid Priority'), ('invalid_sitemap', 'Invalid Sitemap Format'), ('sitemap_error', 'Sitemap Error'), ('ssl_error', 'SSL Certificate Error'), ('other', 'Other Issue'), ('lcp_poor', 'Poor Largest Contentful Paint'), ('cls_poor', 'Poor Cumulative Layout Shift'), ('inp_poor', 'Poor Interaction to Next Paint'), ('fid_poor', 'Poor First Input Delay'), ('semantic_structure', 'Invalid Semantic HTML Structure'), ('viewport_missing', 'Missing Viewport Meta Tag'), ('viewport_invalid', 'Invalid Viewport Configuration'), ('duplicate_titles', 'Duplicate Title Tags'), ('redirect_chain', 'Redirect Chain Detected'), ('redirect_loop', 'Redirect Loop Detected'), ('modern_image_format', 'Not Using Modern Image Format'), ('responsive_images', 'Missing Responsive Image Setup'), ('robots_misconfiguration', 'Robots.txt Misconfiguration'), ('noindex_detected', 'Noindex Tag Detected'), ('indexing_blocked', 'Indexing Blocked by X-Robots-Tag'), ('author_missing', 'Missing Author Information'), ('expertise_signals', 'Missing Expertise Signals'), ('factual_accuracy', 'Potential Factual Accuracy Issues'), ('performance_poor', 'Poor Performance Score'), ('performance_render-blocking-resources', 'Render-Blocking Resources'), ('performance_unoptimized-images', 'Unoptimized Images'), ('performance_unused-css', 'Unused CSS'), ('performance_unused-javascript', 'Unused JavaScript'), ('performance_server-response-time', 'Slow Server Response'), ('pagespeed_error', 'PageSpeed Analysis Error')], max_length=50),
        ),
    ]
