# Generated by Django 5.1.2 on 2025-01-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0002_alter_seoauditissue_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEORemediationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_provider', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('plan_content', models.JSONField(help_text='Structured remediation plan content')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='seo_audit.seoauditresult')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('audit', 'url')},
            },
        ),
    ]
