# Generated by Django 5.1.2 on 2025-01-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0003_seoremediationplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seoremediationplan',
            unique_together=set(),
        ),
    ]
