# Generated by Django 5.1.6 on 2025-03-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_logo'),
        ('seo_audit', '0004_remove_remediation_plan_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoauditresult',
            name='organization',
            field=models.ForeignKey(default='091a9243-73d4-4691-b143-298b2ecb3836', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
