# Generated by Django 5.1.7 on 2025-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_audit', '0005_seoauditresult_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoauditresult',
            name='crawl_mode',
            field=models.CharField(default='auto', help_text='Crawl mode: auto, sitemap, or discovery', max_length=20),
        ),
    ]
