# Generated by Django 5.1.6 on 2025-03-06 17:22

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_create_default_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.SecureFileStorage(collection='organization_logos', private=True), upload_to=''),
        ),
    ]
