# Generated by Django 5.1.5 on 2025-02-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='guidance',
            field=models.TextField(blank=True, help_text='Optional guidance for content processing', null=True),
        ),
    ]
