# Generated by Django 5.1.5 on 2025-02-17 21:49

import apps.research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_research_reasoning_steps_alter_research_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='learnings',
            field=models.JSONField(default=apps.research.models.default_list),
        ),
        migrations.AlterField(
            model_name='research',
            name='reasoning_steps',
            field=models.JSONField(default=apps.research.models.default_list),
        ),
        migrations.AlterField(
            model_name='research',
            name='visited_urls',
            field=models.JSONField(default=apps.research.models.default_list),
        ),
    ]
